### ISSUE TITLE
Add a badge for SwiftPM

### ISSUE THREAD

**Issue by TofPlay** [JohnSundell/Files#1]
Hi,
If your component is compatible with SwiftPM it's will be good to add this badge 🙂
[![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://swift.org/package-manager/)

**Comment by JohnSundell** [comment]
Good idea @TofPlay, will do! 👍

**Comment by JohnSundell** [comment]
Done! ✅
