### ISSUE TITLE
Support glob

### ISSUE THREAD

**Issue by yonaskolb** [JohnSundell/Files#20]
It would be great to have a way of getting all files in a folder using a glob pattern
```
let files = folder.glob("*.swift")
```
You could use `Glibc.glob` on Linux and `Darwin.glob` on Darwin

**Comment by JohnSundell** [comment]
@yonaskolb Sounds like an interesting addition 👍 Do you want to submit a PR adding this new feature?

**Comment by JohnSundell** [comment]
Ping @yonaskolb. Interested in adding this? Otherwise I'll probably close this for now 🙂

**Comment by yonaskolb** [comment]
@JohnSundell sorry I haven't had time for this recently. You're welcome to close it for now

**Comment by JohnSundell** [comment]
@yonaskolb No worries, just wanted to check in 🙂 I'll close for now then, but feel free to open a PR in the future to add this, I think it'd be an interesting addition even though it's not something that I need myself at the moment.
