### ISSUE TITLE
Copying, not moving

### ISSUE THREAD

**Issue by artemnovichkov** [JohnSundell/Files#22]
Hi, John! I want to copy existing file to another folder. How I can do it? I found only `Item.move(to:)` method, but I want to keep original file.

**Comment by JohnSundell** [comment]
Hey @artemnovichkov 👋 What you can do is to read the file using `file.read()`, and then write that data to a new file using `newFolder.createFile(named: "MyFile", contents: data)`. We could also add a `copy()` method for `File`. Something you'd like to implement and submit a PR?

**Comment by artemnovichkov** [comment]
Yes, that was my implementation. Yes, with pleasure, will try to file some time

**Comment by JohnSundell** [comment]
Awesome 👍

**Comment by JohnSundell** [comment]
New version containing these changes (1.12.0) has been released (also on CocoaPods) 🚀 Thanks again @artemnovichkov 🎉
