### ISSUE TITLE
Recursive renaming

### ISSUE THREAD

**Issue by artemnovichkov** [JohnSundell/Files#26]
I want to rename some folders recursively. For example, I have a folder structure:
```
Folder1
-Folder2
```
And I want to replace "Folder" word with "Project" word. When I use `Folder.makeSubfolderSequence(recursive:includeHidden:)` method, I can't rename `Folder2` after `Folder1` renaming, because it has old path - `Folder1/Folder2`. How I can deal with it? Maybe `Item.rename(to:keepExtension:)` method should update paths of subfolders?

**Comment by JohnSundell** [comment]
Yeah this is an interesting one. Seems like it's not propagated in the iteration. Would love it if you could have a look at this one and submit a PR with a fix, if you have time 👍

**Comment by artemnovichkov** [comment]
I guess it would be difficult, because it's `Item` method, not only `Folder` class. Can you suggest any vectors of implementation?

**Comment by VFUC** [comment]
@artemnovichkov I think for your case, it could be sufficient to just reverse the sequence before iterating over it. This worked for me:

```
$ tree
.
└── Folder1
    └── Folder2
```
```
for folder in try Folder(path: ".").makeSubfolderSequence(recursive: true, includeHidden: false).reversed() {
	try folder.rename(to: "renamed")
}
```
```
$ tree
.
└── renamed
    └── renamed
```

**Comment by LarsJK** [comment]
Think I can fix this. Will work on a PR tonight..
