### ISSUE TITLE
newb question: why use strings instead of URLs?

### ISSUE THREAD

**Issue by jeff-h** [JohnSundell/Files#29]
Just wondering why Files uses strings instead of URLs?  

Apple [states](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Strings/Articles/ManipulatingPaths.html):

> Where possible, you should use instances of NSURL to represent paths—the operating system deals with URLs more efficiently than with string representations of paths.

Sorry if this "meta" question is out of place in the issue queue.

**Comment by JohnSundell** [comment]
Hey @jeff-h 👋 Mostly for convenience, Files is mainly geared towards Swift tools and scripts, so it tries to reduce API "overhead" as much as possible - and using strings is part of that 🙂

**Comment by jeff-h** [comment]
Ah, makes sense :) Thanks.
