### ISSUE TITLE
Can't load underlying module for 'Files'

### ISSUE THREAD

**Issue by guoyingtao** [JohnSundell/Files#33]
My Xcode is 9.0.1, macOS 10.12.6. I used cocoapods(1.3.1) to integrate this library (1.12.0).
After that, I can see a new folder named "Files" under my "Pods" folder
When I tried to use "import Files", I got this compile error - "Can't load underlying module for 'Files'"
Can you help me to work it out? Thank you.

**Comment by JohnSundell** [comment]
@guoyingtao I'll try, but will need some more information. Do you get any error when running `pod install` on the command line? Did you try cleaning the project and then re-building?

**Comment by guoyingtao** [comment]
Just solved it.
I need to set "Swift Language Version" to "4.0" for my project setting.
Before it was "unspecified".
Thanks for your reply!

**Comment by JohnSundell** [comment]
Awesome 👍
