### ISSUE TITLE
[Enquiry] Iterate over files with filetype in current directory

### ISSUE THREAD

**Issue by lf-araujo** [JohnSundell/Files#35]
Dear John,

Thank you for the excellent lib. I am trying to learn how to use it. How can I iterate over all files with `.md` extension in the current folder?

I am stuck with:

```
for file in try Folder(path: Folder.current).files {
...
}
```

What is the proper use?

Thank you.

**Comment by JohnSundell** [comment]
Hi @lf-araujo 👋 

Here's how to do it:

```swift
for file in Folder.current.files {
    guard file.extension == "md" else {
        continue
    }

    // Your code here
}
```
