### ISSUE TITLE
Adding file append

### ISSUE THREAD

**Issue by ikhsan** [JohnSundell/Files#48]
Thanks for `Files`! I wrote a script with it for a database validation task at work, had a very nice warm feeling being able to write Swift scripts 😄 

I have a suggestion though,  I was a bit surprised that `Files`'s writes only override but no support for appending. Can we have file append? Similar to `>>` in bash.

I'm happy to create a PR, but I want to make sure if this sounds like a good addition. I'm thinking to add new methods `func append(data: Data) throws` and its string counterpart. Or, we could change write to `func write(data: Data, shouldAppend: Bool = false) throws`. I prefer the former though, let me know what you think.

**Comment by JohnSundell** [comment]
Hi @ikhsan! 👋 Awesome to hear that you're getting into Swift scripting 👍 I agree, let's do the former:

```swift
func append(data: Data) throws
```

Think it would be a great addition to the framework, happy to accept a PR adding it 🙂

**Comment by ikhsan** [comment]
Awesome stuff! 👌

As the PR is ready #49, I'm closing this issue.
