### ISSUE TITLE
error: cannot invoke initializer for type 'Bool' with an argument list of type '(ObjCBool)'

### ISSUE THREAD

**Issue by futurejones** [JohnSundell/Files#55]
Hi, I am using Swift 4.1 on Linux Debian and I am getting the following error.
```
/home/rock64/FileCreator/.build/checkouts/Files.git-4953067514002805256/Sources/Files.swift:1040:34: error: cannot invoke initializer for type 'Bool' with an argument list of type '(ObjCBool)'
    var boolValue: Bool { return Bool(self) }

```

**Comment by kezzico** [comment]
ObjCBool looks like this on MacOS

public struct ObjCBool : ExpressibleByBooleanLiteral {

    public init(_ value: Bool)

    /// The value of `self`, expressed as a `Bool`.
    public var boolValue: Bool { get }

    /// Create an instance initialized to `value`.
    public init(booleanLiteral value: Bool)
}

**Comment by JohnSundell** [comment]
Files should now be fully Linux-compatible, however, it currently only supports Swift 5.0 and above.
