### ISSUE TITLE
ContainsFile API

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/Files#60]
When asking if a folder contains a file, the API is currently

```
let folder = try Folder(named: "Foo")
let contains: Bool = folder.containsFile(named: "NameOfFile")
```

Could we extend this to handle an actual file variable instead?

```
let file: File = ...
let folder = try Folder(named: "Foo")
let contains: Bool = folder.containsFile(file)
```

An interesting point to add: I was getting a false result when using `name` instead of `nameExcludingExtension`.

```
let name = file.nameExcludingExtension
let doesContain = folder.containsFile(named: name) // true
```

```
let name = file.name
let doesContain = folder.containsFile(named: name) // false
```

I can understand why this happens, but it was unexpected at first.

**Comment by clayellis** [comment]
In order to stay in line with the Foundation APIs, let's change the method signature from `containsFile(_ file: File)` to `contains(_ file: File)` (`folder.contains(file)`).

**Comment by clayellis** [comment]
@rob-nash Are you working on a PR or is this open to anyone for implementation?

**Comment by JohnSundell** [comment]
Sounds like a great addition 👍 Agree with @clayellis that the new method should be called `contains(_ file: File)`, and we could (not necessarily now) also add a `contains(_ folder: Folder)` overload as well.

**Comment by rob-nash** [comment]
@clayellis No, this is open for implementation. 👍🏼

**Comment by clayellis** [comment]
Starting an PR for this
