### ISSUE TITLE
Object-oriented implementations

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/Files#68]
Hi,

There seems to be a danger passing `File` around, by reference.

If I have the following

```
let file = try folder.file(named: "name.pdf")
```

And I pass it into the following function.

```
func store(_ file: File) throws
```

Moving forward, if I interact with this same `File` reference, it may no longer have a valid path. The `store` function above may perform `moveItem`, for example.

### Idea 1
Perhaps we could create an alias?

### Idea 2
Might it be worth making a distinction between a `File` that you know exists and a `PotentialFile` that hasn't been confirmed to exist? You see this kind of 'evaluate at last minute' mentality throughout Swift.

The same kind of mentality as

- A slice of a string or array
- Copy on write
- An optional has .some or .none

I suppose we would have to handle a change in state, in both directions.

- `PotentialFile` becoming `File`
- `File` becoming `PotentialFile`

### Idea 3

Perhaps we could harness this API?

[FileReferenceURL](https://developer.apple.com/documentation/foundation/nsurl/1408631-filereferenceurl)

[Check Resource Is Reachable](https://developer.apple.com/documentation/foundation/nsurl/1410597-checkresourceisreachableandretur?language=objc)

**Comment by rob-nash** [comment]
Actually, could we just update the path on the `File` instance, from within the implementation of `move`.

**Comment by rob-nash** [comment]
Just wrote a test and I couldn't reproduce the issue. Started looking at other reason why this might be happening and it turns out I'm running code on the wrong thread.

Thanks for helping me think 'outside of the box'.

Sorry for wasting time.

**Comment by clayellis** [comment]
Never a waste! Glad to help 👍
