### ISSUE TITLE
try file.write(data: wrap(object)) - use of unresolved identifier 'wrap'

### ISSUE THREAD

**Issue by johndpope** [JohnSundell/Files#7]

**Comment by JohnSundell** [comment]
Uhm what? 😅 What is this issue for @johndpope?

**Comment by johndpope** [comment]
it's actually referenced in the samples
let folder = try Folder(path: "/users/john/folder")
let file = try folder.createFile(named: "file.json")
try file.write(data: wrap(object)) // <- here are you using another library?
try file.delete()
try folder.delete()

**Comment by JohnSundell** [comment]
Ah right, now I see what you mean. Yes, in the README sample code [Wrap](https://github.com/johnsundell/wrap) is used. It's just an example though, you can pass any `Data` to `file.write()`.

**Comment by JohnSundell** [comment]
But you do have a point, it's a bit strange to reference another library implicitly like that in the README. I've now replaced that example with an inline string. Thanks for bringing this up 🙂
