### ISSUE TITLE
Cannot create new folders

### ISSUE THREAD

**Issue by RJ-Clegg** [JohnSundell/Files#71]
Hey @JohnSundell 

Love the work you're doing for the community! 

I must be doing something stupid as I just cannot figure this out. I am testing Files, for the first time and followed the read me. So, I created a script with the very following: 

```
let folder = try Folder(path: "/Users/robert/TestFolder")
let file = try folder.createFile(named: "file.json")
try file.write(string: "{\"hello\": \"world\"}")
```

**What I expected**

For a folder named 'TestFolder' to be created in the `/Users/robert/` directory

**What actually happened**

I received the following error in Terminal

> 💥  Failed to run script
> 👉  Fatal error: Error raised at top level: Invalid path given: /Users/robert/TestFolder/: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.37.1/src/swift/stdlib/public/core/ErrorType.swift, line 191
>    /bin/bash: line 1: 21533 Illegal instruction: 4  /Users/robert/.marathon/Scripts/Cache/-Users-robert-Developer-MyApp-Scripts-TestScript/.build/debug/TestScript

Is there something I am misunderstanding or doing wrong here? 

If I create the folder manually, the script works and adds the `file.json` to the folder. Its the folder creation that seems to be the issue. 

Appreciate any insight / help into this

**Comment by appinator** [comment]
Catch the error and let Files create a folder before continuing with file creation.

**Comment by RJ-Clegg** [comment]
Thanks @appinator that is what I eventually ended up doing.

**Comment by sabiland** [comment]
So there isn't an option JUST to create folder via `let folder = try Folder(path: "/Users/robert/TestFolder")` ?
