### ISSUE TITLE
Should .xcodeproj be gitignored?

### ISSUE THREAD

**Issue by hisaac** [JohnSundell/Files#72]
What are your thoughts on removing the `.xcodeproj` from the repo in favor of generating it using `swift package generate-xcodeproj`?

I was going to submit a quick PR to update Files to Swift 4.2, but I noticed that the `.xcodeproj` is committed to the repo. I was going to gitignore it, since that seems recommended for SPM libraries, but I wanted to ask first.

**Comment by JohnSundell** [comment]
Hey @hisaac. We can't ignore the Xcode project, since that would make Files incompatible with other package managers - like Carthage, SwiftPM is not the only package manager supported 🙂

**Comment by hisaac** [comment]
Ah ok, that makes sense. Thank you for the clarification.
