### ISSUE TITLE
Possibility obtaining bytesWritten/totalBytesInFile

### ISSUE THREAD

**Issue by tresrrr** [JohnSundell/Files#85]
First of all thanks for a great job like "Files";

It would be great to obtain bytesWritten/totalBytesInFile. 
This way it would be possible to control the traffic and implement progressIndicators or some other visual progress help.

Thanks for all.

**Comment by JohnSundell** [comment]
Files is mainly aimed towards scripts and command line tools, so it performs all of its work synchronously - so it's probably not a good fit if you want to asynchronously write large files and show a progress indicator while that's happening.
