### ISSUE TITLE
Protect the user’s data using encryption

### ISSUE THREAD

**Issue by AdAvAn** [JohnSundell/Files#86]
Good day.

Is it possible to expand the current methods of writing and reading files, adding the ability to use encryption, as is common in the  [documentation](https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files)?

Thank you!

**Comment by JohnSundell** [comment]
That's beyond the scope of Files. Please use an encryption library/framework for that purpose.
