### ISSUE TITLE
Changes in v4.0.0

### ISSUE THREAD

**Issue by RjwBn** [JohnSundell/Files#90]
Since upgrading to 4.0.0 and Xcode 11 two features seem to have disappeared. 
file.copy used to return a reference to the new file.
![Screenshot 2019-09-24 at 06 52 27](https://user-images.githubusercontent.com/55734109/65490414-01a3e880-dea5-11e9-9f83-f49afb2d709e.png)

FileSystem().createFolderIfNeeded no longer exists.

![Screenshot 2019-09-24 at 08 18 46](https://user-images.githubusercontent.com/55734109/65490473-24360180-dea5-11e9-8d0d-a81f5650ccd1.png)

Are these depreciated?

Thanks

**Comment by JohnSundell** [comment]
@RjwBn I recommend reading the release notes before updating to a new version of a framework. You can find the 4.0 release notes [here](https://github.com/JohnSundell/Files/releases/tag/4.0.0), which tell you how to migrate from `FileSystem` to `Folder.root`. The fact that the `copy` doesn't return a new instance anymore is a regression (it wasn't covered by any tests, so I missed it). Will fix it shortly 👍

**Comment by JohnSundell** [comment]
Fix here: https://github.com/JohnSundell/Files/pull/91

**Comment by JohnSundell** [comment]
The patch for `copy` has now been released as version `4.0.1` 👍

**Comment by RjwBn** [comment]
Thanks for pointing me at the release notes. I've noted for future.
And thanks for the great work.
Can I buy you a coffee?
