### ISSUE TITLE
Folder.documents doesn't seem to work

### ISSUE THREAD

**Issue by thejeff77** [JohnSundell/Files#96]
Hey there! I'm wondering if I'm doing something wrong...

I've imported the library with swift package manager, and added (import Files) at the top of the swift file.

This is the build output: 

<img width="605" alt="Screen Shot 2019-10-05 at 8 36 46 AM" src="https://user-images.githubusercontent.com/8584457/66256471-62f07500-e74b-11e9-8b2f-76c580941b71.png">

With Swift 5.1 and Xcode 11 GE

**Comment by princegeovision** [comment]
Folder.documents, and Folder.library are macOS only for some reason.
I use extension to add them back to use in iOS. maybe you can do the same.

```
#if os(iOS)
extension Folder {
    
    static var documents: Folder? {
        let urls = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
        guard let url = urls.first else { return nil }
        return try? Folder(path: url.relativePath)
    }
    /// The current user's Library folder
    static var library: Folder? {
        let urls = FileManager.default.urls(for: .libraryDirectory, in: .userDomainMask)
        guard let url = urls.first else { return nil }
        return try? Folder(path: url.relativePath)
    }
}
#endif
```

**Comment by thejeff77** [comment]
Awesome. Thanks! 

I'd kind of like to get a comment from @JohnSundell - I'd be interested why this was made only for macOS, and if it was done for good reason. I'd like to fix it in the library itself the right way if possible.

**Comment by thejeff77** [comment]
@princegeovision do both of these work? I didn't know there was a library folder on iOS.

**Comment by princegeovision** [comment]
Well, I never use "library" as well, but apparently it has.

```
library = Folder(name: Library, path: /Users/xxxxxxxxxx/Library/Developer/CoreSimulator/Devices/AC788231-BC9D-4C31-A32A-C580AEBD2659/data/Containers/Data/Application/0F0BC8D9-32D5-46B8-A396-1B9C79D3A5EA/Library/)
documents = Folder(name: Documents, path: /Users/xxxxxxxxxx/Library/Developer/CoreSimulator/Devices/AC788231-BC9D-4C31-A32A-C580AEBD2659/data/Containers/Data/Application/0F0BC8D9-32D5-46B8-A396-1B9C79D3A5EA/Documents/)
```

**Comment by ducnguyenenterprise** [comment]
@princegeovision You can make a pull requet, hope @JohnSundell can make it the offical

**Comment by BowdusBrown** [comment]
```swift
let documents = try! Folder.home.subfolder(named: "Documents")
```

**Comment by JohnSundell** [comment]
Feel free to make a PR if you'd like to see these APIs added on iOS 👍 Files was originally developed with a heavy focus on macOS, since it was primarily built for command line tools and scripting, which is why some of its APIs are a bit Mac-centric.
